version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./apache.conf:/etc/apache2/sites-available/000-default.conf
      - ./src:/var/www/html
    ports:
      - 8080:80
      - 3000:3000
    links:
      - database
    environment:
      XDEBUG_CONFIG: remote_host=172.17.0.1
      PHP_IDE_CONFIG: "serverName=development"

  database:
    image: postgres:latest
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=secret
